[tool.poetry]
name = "lagomorph"
version = "0.1.0"
description = "Fork of CleanRL focused on DQN training"
packages = [
    { include = "envs" },
    { include = "utils" },
]
keywords = ["reinforcement", "machine", "learning", "research"]
license="MIT"
readme = "README.md"